markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  fenced_code_blocks: true
  syntax_highlighter: rouge

#
# highlighter: rouge
#highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: SHML
tagline: '$(shell markup language)'
description: 'SHML is a shell framework for faster and easier script development.'
url: https://github.com/odb/shml/
baseurl: /shml/

# paginate: 1

# Custom vars
version: 1.0.4
